version: '3.3'
services:
  evepraisal:
    container_name: stevepraisal
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8088:8080
      - 8094:8081
    volumes:
      - ./evepraisal.toml:/evepraisal/evepraisal.toml
    restart: always
